### ISSUE TITLE
current project's "pull request" allowance

### ISSUE THREAD

**Issue by dcabale** [tothpaul/DelphiTips.LinkEditor#1]
Hello,
Although not familiar with GitHub "pull requests", it seems the current GitHub project does not give me the opportunity to create my own branch from the project's main branch
![image](https://user-images.githubusercontent.com/1404724/192229302-eda1ee93-5ac3-459e-af31-2d61b16a44fa.png)
just as the [GitHub documentation on "Creating the pull request"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request#creating-the-pull-request) describes.
-> Would you be able to adjust /explain?
Thanks in advance

**Comment by dcabale** [comment]
Issue sorted out..
Though not precised by the [GitHub documentation on "Creating the pull request"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request#creating-the-pull-request), here are the necessary prerequisites for being able to initiate a "pull request":
1. create a GitHub private "Fork" of the current project, for which a pull request is intended.
![image](https://user-images.githubusercontent.com/1404724/192602020-a871175d-3995-428a-b425-e55335ae841d.png)
2. check-out this private "Fork" to your PC (local copy of that fork)
![image](https://user-images.githubusercontent.com/1404724/192604083-046b8176-784b-41f2-826c-115b18a5b522.png)
3. do your changes in your local copy
4. check-in your changes to your GitHub private "Fork".
Note that while checking-in to GitHub, you can be annoyed by authentication failure. To get rid of this, read here -> https://ginnyfahs.medium.com/github-error-authentication-failed-from-command-line-3a545bfd0ca8
5. now you can follow the  [GitHub documentation on "Creating the pull request"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request#creating-the-pull-request)

**Comment by tothpaul** [comment]
oui c'est pénible :) il faut faire un fork et soumettre la modif :)
